:page-layout: certification 
= TCK Results

As required by the https://www.eclipse.org/legal/tck.php[Eclipse Foundation Technology Compatibility Kit License], following is a summary of the TCK results for releases of MicroProfile Telemetry 1.0

== Open Liberty 23.0.0.3 - MicroProfile Telemetry 1.0 Certification Summary (Java 11)

* Product Name, Version and download URL (if applicable):
+
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/23.0.0.3/openliberty-23.0.0.3.zip[Open Liberty 23.0.0.3]

* Specification Name, Version and download URL:
+
https://github.com/eclipse/microprofile-telemetry/tree/1.0[MicroProfile Telemetry 1.0 Specification]

* (Optional) TCK Version, digital fingerprint and download URL:
+
https://repo1.maven.org/maven2/org/eclipse/microprofile/telemetry/tracing/microprofile-telemetry-tracing-tck/1.0/microprofile-telemetry-tracing-tck-1.0.jar[MicroProfile Telemetry 1.0 TCK]
+
SHA-1: `cc5e4587359c87dbd72d63df8e36c244e25c55f7`
+
SHA-256: `1fe38bb253874be3a44e6ab8bc29108e5c1aff82f54ab06f6401df280ed053b4`

* Public URL of TCK Results Summary:
+
xref:23.0.0.3-MicroProfile-Telemetry-1.0-Java11-TCKResults.adoc[TCK results summary]


* Java runtime used to run the implementation:
+
Java 11: IBM Semeru Runtime Open Edition (11.0.17+8)

* Summary of the information for the certification environment, operating system, cloud, ...:
+
Linux: Linux version 4.18.0-425.3.1.el8.ppc64le (mockbuild@ppc-061.build.eng.bos.redhat.com) (gcc version 8.5.0 20210514 (Red Hat 8.5.0-15) (GCC)) #1 SMP Fri Sep 30 11:30:21 EDT 2022

Test results:

[source, text]
----
Test suite: org.eclipse.microprofile.telemetry.tracing.tck.cdi.TracerTest 2023-03-17T20:35:56 UTC
Tests:1 Failures:0 Errors:0
   org.eclipse.microprofile.telemetry.tracing.tck.cdi.TracerTest.tracer Passed!
Test suite: org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDefaultTest 2023-03-17T20:35:56 UTC
Tests:7 Failures:0 Errors:0
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDefaultTest.spanCurrent Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDefaultTest.spanNew Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDefaultTest.spanChild Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDefaultTest.spanName Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDefaultTest.span Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDefaultTest.spanNameQuery Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDefaultTest.spanError Passed!
Test suite: org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanTest 2023-03-17T20:35:56 UTC
Tests:3 Failures:0 Errors:0
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanTest.spanName Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanTest.spanNameWithoutQueryString Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanTest.span Passed!
Test suite: org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanDisabledTest 2023-03-17T20:35:56 UTC
Tests:3 Failures:0 Errors:0
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanDisabledTest.spanNameWithoutQueryString Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanDisabledTest.spanName Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanDisabledTest.span Passed!
Test suite: org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanTest 2023-03-17T20:35:56 UTC
Tests:7 Failures:0 Errors:0
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanTest.span Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanTest.spanNew Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanTest.spanNameQuery Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanTest.spanCurrent Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanTest.spanError Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanTest.spanChild Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanTest.spanName Passed!
Test suite: org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanDefaultTest 2023-03-17T20:35:56 UTC
Tests:3 Failures:0 Errors:0
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanDefaultTest.spanNameWithoutQueryString Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanDefaultTest.span Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestSpanDefaultTest.spanName Passed!
Test suite: org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDisabledTest 2023-03-17T20:35:56 UTC
Tests:7 Failures:0 Errors:0
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDisabledTest.spanName Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDisabledTest.spanNameQuery Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDisabledTest.spanChild Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDisabledTest.spanCurrent Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDisabledTest.spanNew Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDisabledTest.span Passed!
   org.eclipse.microprofile.telemetry.tracing.tck.rest.RestClientSpanDisabledTest.spanError Passed!
Test suite: org.eclipse.microprofile.telemetry.tracing.tck.rest.BaggageTest 2023-03-17T20:35:56 UTC
Tests:1 Failures:0 Errors:0
   org.eclipse.microprofile.telemetry.tracing.tck.rest.BaggageTest.baggage Passed!
Test suite: org.eclipse.microprofile.telemetry.tracing.tck.TestApplication 2023-03-17T20:35:56 UTC
Tests:1 Failures:0 Errors:0
   org.eclipse.microprofile.telemetry.tracing.tck.TestApplication.rest Passed!
----