:page-layout: certification
= TCK Results

As required by the https://www.eclipse.org/legal/tck.php[Eclipse Foundation Technology Compatibility Kit License], following is a summary of the TCK results for releases of Jakarta EE Core Profile 10.0.

== Open Liberty 22.0.0.13-beta Jakarta EE Core Profile 10.0 using Java 11 Certification Summary

* Product Name, Version and download URL (if applicable):
+
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/beta/22.0.0.13-beta/openliberty-22.0.0.13-beta.zip[Open Liberty 22.0.0.13-beta]

* Specification Name, Version and download URL:
+
https://jakarta.ee/specifications/coreprofile/10[Jakarta EE Core Profile 10.0]

* TCK Version, digital SHA-256 fingerprint and download URL:
+
https://download.eclipse.org/jakartaee/coreprofile/10.0/jakarta-core-profile-tck-10.0.1.zip[Jakarta EE Core Profile TCK 10.0.1],
SHA-256: `0fa5ead035817dc8e408354d9a70053802383d503fe1413abb33491daba263f8`

* Public URL of TCK Results Summary:
+
link:22.0.0.13-beta-Java11-TCKResults.html[TCK results summary]

* Any Additional Specification Certification Requirements:
+
Jakarta Annotations
https://download.eclipse.org/jakartaee/annotations/2.1/jakarta-annotations-tck-2.1.1.zip[jakarta-annotations-tck-2.1.1.zip], SHA-256:
  `8c2131d51c75cde4be74382f662519f9fd439f4ce4dd60832ed55b796e5f72f3`
+
Jakarta Contexts and Dependency Injection
https://download.eclipse.org/ee4j/cdi/4.0/cdi-tck-4.0.7-dist.zip[cdi-tck-4.0.7-dist.zip], SHA-256:
  `683e09ed991b61992a491857345cce635dd9e61a1f17663e2fb993c9d0f6b781`
+
Jakarta Dependency Injection
https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.2-bin.zip[jakarta.inject-tck-2.0.2-bin.zip], SHA-256:
  `23bce4317ca061c3de648566cdf65c74b57e1264d6891f366567955d6b834972`
+
Jakarta JSON Binding
https://download.eclipse.org/jakartaee/jsonb/3.0/jakarta-jsonb-tck-3.0.0.zip[jakarta-jsonb-tck-3.0.0.zip], SHA-256:
  `954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b`
+
Jakarta JSON Processing
https://download.eclipse.org/jakartaee/jsonp/2.1/jakarta-jsonp-tck-2.1.1.zip[jakarta-jsonp-tck-2.1.1.zip], SHA-256:
  `949f203de84deffa8c7892b555918e42f1dd220ccb7b6800741ea58af62737c1`
+
Jakarta RESTful Web Services
https://download.eclipse.org/jakartaee/restful-ws/3.1/jakarta-restful-ws-tck-3.1.2.zip[jakarta-restful-ws-tck-3.1.2.zip], SHA-256:
  `d854850faf1ab09279f515fef052de5e57afbc591e72d071337e08f0edf41d25`


* Java runtime used to run the implementation:
+
----
java version "11.0.15" 2022-04-19
IBM Semeru Runtime Certified Edition 11.0.15.0 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Linux amd64-64-Bit Compressed References 20220427_337 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - da9a227f69 based on jdk-11.0.15+10)
----

* Summary of the information for the certification environment, operating system, cloud, ...:
+
Apache Derby, Linux, Ubuntu 18.04


Test results:

----
Stage Name: Annotations TCK
[javatest.batch] ********************************************************************************
[javatest.batch] Completed running 1 tests.
[javatest.batch] Number of Tests Passed      = 1
[javatest.batch] Number of Tests Failed      = 0
[javatest.batch] Number of Tests with Errors = 0
[javatest.batch] ********************************************************************************
[javatest.batch] PASSED........com/sun/ts/tests/signaturetest/caj/CAJSigTest.java#signatureTest
[javatest.batch] 
[javatest.batch] Total time = 17s


Stage Name: CDI TCK
[INFO] Tests run: 725, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 972.445 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 725, Failures: 0, Errors: 0, Skipped: 0

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.367 s - in org.jboss.weld.langmodel.tck.LangModelTckTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] /jakarta/conf/cdi-tck/target/surefire-reports/sigtest/TEST-liberty-cdi-tck-runner-4.0.7.xml: 0 failures in /jakarta/conf/cdi-tck/target/api-signature/cdi-api-jdk11.sig
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.499 s


Stage Name: Core TCK
[INFO] Results:
[INFO] 
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M7:verify (verify) @ core-profile-tck-runner ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:14 min


Stage Name: Dependency Injection TCK
[INFO] Tests run: 50, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.167 s - in weld.SampleBootstrapTCK
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 50, Failures: 0, Errors: 0, Skipped: 0


Stage Name: JSON Binding TCK
[INFO] Results:
[INFO] 
[WARNING] Tests run: 295, Failures: 0, Errors: 0, Skipped: 5


Stage Name: JSON Processing TCK
[INFO] Results:
[INFO] 
[INFO] Tests run: 179, Failures: 0, Errors: 0, Skipped: 0

[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.77 s - in ee.jakarta.tck.jsonp.pluggability.jsonprovidertests.ClientTests
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0


Stage Name: RESTful Web Services TCK
[INFO] Results:
[INFO] 
[WARNING] Tests run: 2647, Failures: 0, Errors: 0, Skipped: 127
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M7:verify (verify) @ jakarta-restful-ws-tck-runner ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:03 min
----
