:page-layout: certification
= TCK Results

As required by the https://www.eclipse.org/legal/tck.php[Eclipse Foundation Technology Compatibility Kit License], following is a summary of the TCK results for releases of Jakarta EE Core Profile 10.0.

== Open Liberty 22.0.0.10-beta Jakarta EE Core Profile 10.0 using Java 11 Certification Summary

* Product Name, Version and download URL (if applicable):
+
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/beta/22.0.0.10-beta/openliberty-22.0.0.10-beta.zip[Open Liberty 22.0.0.10-beta]

* Specification Name, Version and download URL:
+
https://jakarta.ee/specifications/coreprofile/10[Jakarta EE Core Profile 10.0]

* TCK Version, digital SHA-256 fingerprint and download URL:
+
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-core-profile-tck-10.0.0.zip[Jakarta EE Core Profile TCK 10.0 (Staged Release)],
SHA-256: `702a84e3c6532fb0aad6a37443bf5e7fadbfb7cf0071271f3a1fdd10cab1229c`

* Public URL of TCK Results Summary:
+
link:22.0.0.10-beta-Java11-TCKResults.html[TCK results summary]

* Any Additional Specification Certification Requirements:
+
Jakarta Annotations
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-annotations-tck-2.1.1.zip[jakarta-annotations-tck-2.1.1.zip (Staged Release)], SHA-256:
  `8c2131d51c75cde4be74382f662519f9fd439f4ce4dd60832ed55b796e5f72f3`
+
Jakarta Contexts and Dependency Injection
https://download.eclipse.org/ee4j/cdi/4.0/cdi-tck-4.0.7-dist.zip[cdi-tck-4.0.7-dist.zip], SHA-256:
  `683e09ed991b61992a491857345cce635dd9e61a1f17663e2fb993c9d0f6b781`
+
Jakarta Dependency Injection
https://download.eclipse.org/ee4j/cdi/inject/2.0/jakarta.inject-tck-2.0.2-bin.zip[jakarta.inject-tck-2.0.2-bin.zip], SHA-256:
  `23bce4317ca061c3de648566cdf65c74b57e1264d6891f366567955d6b834972`
+
Jakarta JSON Binding
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/promoted/eftl/jakarta-jsonb-tck-3.0.0.zip[jakarta-jsonb-tck-3.0.0.zip], SHA-256:
  `954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b`
+
Jakarta JSON Processing
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/promoted/eftl/jakarta-jsonp-tck-2.1.0.zip[jakarta-jsonp-tck-2.1.0.zip], SHA-256:
  `6ee953382ff965627fe20dd7e3bfce6c968ed829d611cf4990988ab54bfe8b54`
+
Jakarta RESTful Web Services
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-restful-ws-tck-3.1.1.zip[jakarta-restful-ws-tck-3.1.1.zip (Staged Release)], SHA-256:
  `2ff33625931c5df8631a016bd25daabed9b27c81d72b7d2bfe6cab21b121cf1b`


* Java runtime used to run the implementation:
+
----
openjdk version "11.0.15" 2022-04-19
IBM Semeru Runtime Certified Edition 11.0.15.0 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Linux amd64-64-Bit Compressed References 20220422_425 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - b7b5b42ea6 based on jdk-11.0.15+10)
----

* Summary of the information for the certification environment, operating system, cloud, ...:
+
Apache Derby, Linux, Ubuntu 18.04

* Challenges
+
https://github.com/jakartaee/rest/issues/1126[RESTful Web Services TCK Challenge]
+
https://github.com/jakartaee/rest/issues/1128[RESTful Web Services - excluded SEBootstrap tests]


Test results:

----
Stage Name: Annotations TCK
[javatest.batch] ********************************************************************************
[javatest.batch] Completed running 1 tests.
[javatest.batch] Number of Tests Passed      = 1
[javatest.batch] Number of Tests Failed      = 0
[javatest.batch] Number of Tests with Errors = 0
[javatest.batch] ********************************************************************************
[javatest.batch] PASSED........com/sun/ts/tests/signaturetest/caj/CAJSigTest.java#signatureTest


Stage Name: CDI TCK
[INFO] Tests run: 725, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,017.849 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 725, Failures: 0, Errors: 0, Skipped: 0

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.881 s - in org.jboss.weld.langmodel.tck.LangModelTckTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] /jakarta/conf/cdi-tck/target/surefire-reports/sigtest/TEST-liberty-cdi-tck-runner-4.0.5.xml: 0 failures in /jakarta/conf/cdi-tck/target/api-signature/cdi-api-jdk11.sig
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.188 s


Stage Name: Core TCK
[INFO] Results:
[INFO] 
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M6:verify (verify) @ core-profile-tck-runner ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:24 min


Stage Name: Dependency Injection TCK
[INFO] Tests run: 50, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.466 s - in weld.SampleBootstrapTCK
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 50, Failures: 0, Errors: 0, Skipped: 0


Stage Name: JSON Binding TCK
[INFO] Results:
[INFO] 
[WARNING] Tests run: 295, Failures: 0, Errors: 0, Skipped: 5


Stage Name: JSON Processing TCK
[INFO] Results:
[INFO] 
[INFO] Tests run: 179, Failures: 0, Errors: 0, Skipped: 0

[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.08 s - in ee.jakarta.tck.jsonp.pluggability.jsonprovidertests.ClientTests
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0


Stage Name: RESTful Web Services TCK
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientExceptionsIT.shouldThrowMostSpecificWebApplicationException:93 
Expected: jakarta.ws.rs.RedirectionException but: was jakarta.ws.rs.InternalServerErrorException
     but: was <ee.jakarta.tck.ws.rs.spec.client.exceptions.ClientExceptionsIT$$Lambda$624/0x000000002ddb9710@eb1840e6>
[ERROR] Errors: 
[ERROR]   JsonbContextProviderIT.shouldUseApplicationProvidedJsonbInstance:106 » InternalServerError HTTP 500 Internal Server Error
[INFO] 
[ERROR] Tests run: 2647, Failures: 1, Errors: 1, Skipped: 59
----
