:page-layout: certification
= TCK Results (DRAFT)

As required by the https://www.eclipse.org/legal/tck.php[Eclipse Foundation Technology Compatibility Kit License], following is a summary of the TCK results for releases of Jakarta EE Core Profile 10.

== Open Liberty 23.0.0.10-beta Jakarta EE Core Profile 10 using Java 17 Certification Summary

* Product Name, Version and download URL (if applicable):
+
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/beta/23.0.0.10-beta/openliberty-23.0.0.10-beta.zip[Open Liberty 23.0.0.10-beta]

* Specification Name, Version and download URL:
+
https://jakarta.ee/specifications/coreprofile/10[Jakarta EE Core Profile 10]

* TCK Version, digital SHA-256 fingerprint and download URL:
+
https://download.eclipse.org/jakartaee/coreprofile/10.0/jakarta-core-profile-tck-10.0.1.zip[Jakarta EE Core Profile TCK 10.0.1],
SHA-256: `0fa5ead035817dc8e408354d9a70053802383d503fe1413abb33491daba263f8`

* Public URL of TCK Results Summary:
+
link:23.0.0.10-beta-Java17-TCKResults.html[TCK results summary]

* Any Additional Specification Certification Requirements:
+
Jakarta Annotations
https://download.eclipse.org/jakartaee/annotations/2.1/jakarta-annotations-tck-2.1.1.zip[jakarta-annotations-tck-2.1.1.zip],
SHA-256: `8c2131d51c75cde4be74382f662519f9fd439f4ce4dd60832ed55b796e5f72f3`
+
Jakarta Contexts and Dependency Injection
https://download.eclipse.org/jakartaee/cdi/4.0/cdi-tck-4.0.9-dist.zip[cdi-tck-4.0.9-dist.zip],
SHA-256: `3fc1db6a7578df561fd5a3bed4b26415c9cc8ae5ec0e6d907957fbdf5ff5e9f4`
+
Jakarta Dependency Injection
https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.2-bin.zip[jakarta.inject-tck-2.0.2-bin.zip],
SHA-256: `23bce4317ca061c3de648566cdf65c74b57e1264d6891f366567955d6b834972`
+
Jakarta JSON Binding
https://download.eclipse.org/jakartaee/jsonb/3.0/jakarta-jsonb-tck-3.0.0.zip[jakarta-jsonb-tck-3.0.0.zip],
SHA-256: `954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b`
+
Jakarta JSON Processing
https://download.eclipse.org/jakartaee/jsonp/2.1/jakarta-jsonp-tck-2.1.1.zip[jakarta-jsonp-tck-2.1.1.zip],
SHA-256: `949f203de84deffa8c7892b555918e42f1dd220ccb7b6800741ea58af62737c1`
+
Jakarta RESTful Web Services
https://download.eclipse.org/jakartaee/restful-ws/3.1/jakarta-restful-ws-tck-3.1.3.zip[jakarta-restful-ws-tck-3.1.3.zip],
SHA-256: `8ff1e6ee4165ca5444cb181a4a70fcde94b9b3915cad948c7f1a029290b09773`


* REPLACE WITH ACTUAL RESULTS